apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: windsurf-prod
resources:
  - network-policies.yaml
  - postgres-statefulset.yaml
  - postgres-services.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - gpu-workers.yaml
  - ingress-api.yaml
  - ingress-labelbee.yaml
images:
  - name: harbor.tclab.org/windsurf/frontend
    newTag: "f0465222"
  - name: harbor.tclab.org/windsurf/annotation-api
    newTag: "a0200115"
